### ISSUE TITLE
Clean from solution explorer

### ISSUE THREAD

**Issue by royraz** [aldobrynin/CleanBinAndObj#5]
Is it possible to improve it with a right-click on a project/solution on the solution explorer?

So if I RC on the solution- it will delete all Bin Obj and if I RC on a specific project- it will delete only the Bin Obj of that project?

**Comment by yannduran** [comment]
Yes, I came here to add the exact same request. :-) That would be awesome.

Right-clicking the solution  was the first thing I tried to do.

**Comment by aldobrynin** [comment]
I've just published new version with solution/project item context menu on [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=dobrynin.cleanbinandobj). 
Check it out

**Comment by yannduran** [comment]
On the whole it's great! 

However, as I was checking, I noticed that it's leaving some `.cs`, `.cache`, `.baml` files in `obj\Debug` folders. It's a **small** thing, but you may find some people are surprised that **_anything_** at all is left in the `bin` or `obj` folders. It could lessen their confidence in your extension.

Are you just deleting `.dll` files? If you are, I'd suggest simply deleting any `Debug` or `Release` folders found in a project's `obj` & `bin` folders. Less recursion required that way too.

Thank you for your very quick response to @royraz's request.

Edit: further testing shows that it **only** happens when your right-click a **_project_**. If you right-click the **_solution_**, **everything** is deleted in the `bin` & `obj` folders.

**Comment by aldobrynin** [comment]
Hmm, I don't filter out files by extension.
For me it works for all files, including `.cs` and `.cache`. Files could be locked by another process or something else.
I'll look into issue with these files if you tell how can I reproduce it. 

I didn't want to clean only `Debug` and `Release` subfolders, because in my project we had like 10 different configurations and I wanted to clean all of them.
But if you want delete files only from `bin\Debug` and `bin\Release`, you can change it in options:
![image](https://user-images.githubusercontent.com/9074893/83942625-ea701580-a7fd-11ea-8e23-d94dc867dd9c.png)
by default it cleans only `bin` and `obj` (path is relative to project root directory).

**Comment by yannduran** [comment]
Thanks again for the quick reply. I think that your thought that the files might be locked by some process is the most likely cause. VS does weird things like that. I also found it strange that it only seemed to happen when I right-clicked a project, but not when I chose the whole solution.

I'll let you know if this persists, and I can show you how to reproduce it.
